version: "3"

services:
  vote:
    image: duclongdocker/vote 
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: duclongdocker/result 
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: duclongdocker/worker 
    networks:
      - back-tier

  redis:
    image: redis
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:11.19-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
